export const setPlaceholder = (lang: string) => {
	if (lang == 'vi') {
		return {
			lang_chxh: 'CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM<br>Độc lập - Tự do - Hạnh phúc',
			lang_syll: 'SƠ YẾU LÝ LỊCH<br><i>TỰ THUẬT</i>',
			lang_name: 'Họ và tên:',
			lang_bir_day: 'Sinh ngày',
			lang_bir_month: 'tháng',
			lang_bir_year: 'năm',
			lang_bir_w: 'Tại',
			lang_tt_now: 'Nơi ở đăng ký hộ khẩu thường trú hiện nay:',
			lang_tt_now1: 'Nơi ở đăng ký thường trú hiện nay:',
			lang_cmnd: 'Chứng minh thư nhân dân số:',
			lang_w_cmnd: 'Nơi cấp:',
			lang_d_cmnd: 'Ngày',
			lang_m_cmnd: 'tháng',
			lang_y_cmnd: 'năm',
			lang_dt_home: 'Số Điện thoại liên hệ: Nhà riêng',
			lang_dt_tele: 'Di động',
			lang_tb: 'Khi cần báo tin cho ai? ở đâu?:',
			lang_sh: 'Số hiệu:',
			lang_kh: 'Ký hiệu:',
			lang_nick_name: 'Bí danh:',
			lang_nom_name: 'Tên thường gọi:',
			lang_qq: 'Nguyên quán:',
			lang_dt: 'Dân tộc',
			lang_tg: 'Tôn giáo',
			lang_tpgd_scc: 'Thành phần gia đình sau cải cách ruộng đất (hoặc cải tạo công thương nghiệp):',
			lang_tpbt: 'Thành phần bản thân hiện nay:',
			lang_tdvh: 'Trình độ văn hoá:',
			lang_language: 'Ngoại ngữ:',
			lang_tdcm: 'Trình độ chuyên môn:',
			lang_lhdt: 'Loại hình đào tạo:',
			lang_cndt: 'Chuyên ngành đào tạo:',
			lang_knd_d: 'Kết nạp Đảng cộng sản Việt Nam ngày',
			lang_knd_w: 'Nơi kết nạp:',
			lang_dtn_d: 'Ngày vào Đoàn TNCSHCM ngày',
			lang_sk: 'Tình hình sức khoẻ:',
			lang_cc: 'Cao',
			lang_cn: 'Cân nặng',
			lang_nn_cm: 'Nghề nghiệp hoặc trình độ chuyên môn:',
			lang_capbac: 'Cấp bậc:',
			lang_lchn: 'Lương chính hiện nay',
			lang_nnn: 'Ngày nhập ngũ:',
			lang_nxn: 'Ngày xuất ngũ:',
			lang_ld_xn: 'Lý do',
			lang_hcgd: 'Hoàn cảnh gia đình',
			lang_hvt_bo: 'Họ và tên bố:',
			lang_hvt_me: 'Họ và tên mẹ:',
			lang_hvt_ace: 'Họ và tên anh chị em ruột<br><i>(Ghi rõ tên, tuổi, chỗ ở, nghề nghiệp và trình độ chính trị của từng người)</i>',
			lang_hvt_vc: 'Họ và tên vợ hoặc chồng:',
			lang_hvt_cc: 'Họ và tên các con:',
			lang_tuoi: 'Tuổi',
			lang_nn: 'Nghề nghiệp',
			lang_nlv: 'Nơi làm việc:',
			lang_trc_cm: 'Trước cách mạng tháng 8 làm gì? Ở đâu?',
			lang_trong_kc: 'Trong kháng chiến chống thực dân Pháp làm gì? Ở đâu?',
			lang_den_nay: 'Từ năm 1955 đến nay làm gì? Ở đâu? (Ghi rõ tên cơ quan, xí nghiệp hiện nay đang làm)',
			lang_w_hn: 'Chỗ ở hiện nay:',
			lang_hdbt: 'Quy trình hoạt động của bản thân',
			lang_hdbt_b: 'Từ tháng năm<br>đến tháng năm',
			lang_hdbt_ct: 'Làm công tác gì',
			lang_hdbt_w: 'Ở đâu',
			lang_hdbt_cv: 'Giữ chức vụ gì?',
			lang_hdbt_ktkl: 'Khen thưởng và kỷ luật',
			lang_hdbt_kt: 'Khen thưởng:',
			lang_hdbt_kl: 'Kỷ luật:',
			lang_cam_doan: 'Lời cam đoan',
			lang_l_cam_doan:
				'Tôi xin cam đoan những lời khai trên là đúng sự thực và chịu trách nhiệm về những lời khai đó. Nếu sau này cơ quan có thẩm quyền phát hiện vấn đề gì không đúng. Tôi xin chấp hành biện pháp xử lý theo quy định./.',
			lang_xac_nhan: 'Xác nhận của Thủ trưởng Cơ quan,<br>Xí nghiệp, Chủ tịch UBND Xã, Phường',
			lang_ky_ten: 'Người khai ký tên',
			lang_k_ght: '(Ký và ghi rõ họ tên)',
		}
	} else if (lang == 'en') {
		return {
			lang_chxh: 'SOCIALIST REPUBLIC OF VIETNAM<br>Independence - Freedom - Happiness',
			lang_syll: 'CURRICULUM VITAE<br><i>Personal statement</i>',
			lang_name: 'Full name:',
			lang_sex: 'Sex:',
			lang_bir_day: 'Date of birth:',
			lang_bir_month: '-',
			lang_bir_year: '-',
			lang_bir_w: 'In',
			lang_tt_now: 'Permanent address:',
			lang_tt_now1: 'Permanent address:',
			lang_cmnd: 'ID card No.:',
			lang_w_cmnd: 'Place of issue:',
			lang_d_cmnd: 'Date of issue:',
			lang_m_cmnd: '-',
			lang_y_cmnd: '-',
			lang_dt_home: 'Contact: Home phone number:',
			lang_dt_tele: 'Mobile phone number:',
			lang_tb: 'Contact address?',
			lang_sh: 'Serial Number: ',
			lang_kh: 'Code: ',
			lang_nick_name: 'Alias:',
			lang_nom_name: 'Preferred name:',
			lang_qq: 'Native place:',
			lang_dt: 'Ethnic group:',
			lang_tg: 'Religion:',
			lang_tpgd_scc: 'Family’s social status after land reform (or industrial and trade reform):',
			lang_tpbt: 'Personal social status:',
			lang_tdvh: 'Education:',
			lang_language: 'Foreign language:',
			lang_tdcm: 'Professional qualification:',
			lang_lhdt: 'Training mode:',
			lang_cndt: 'Major:',
			lang_knd_d: 'Date of joining the Communist Party of Vietnam:',
			lang_knd_w: 'Place of joining:',
			lang_dtn_d: 'Date of joining the Ho Chi Minh Communist Youth Union:',
			lang_sk: 'Health status:',
			lang_cc: 'Height:',
			lang_cn: 'Weight:',
			lang_nn_cm: 'Occupation/ or qualification:',
			lang_capbac: 'Ranking:',
			lang_lchn: 'Main salary:',
			lang_nnn: 'Date of joining Army:',
			lang_nxn: 'Date of demobilization: ',
			lang_ld_xn: 'Reason:',
			lang_hcgd: 'FAMILY STATUS',
			lang_hvt_bo: "Father's full name:",
			lang_hvt_me: "Mother's full name:",
			lang_hvt_ace: 'FULL NAME OF SIBLINGS<br><i>(Full name, age, address, and occupation and political qualifications of each)</i>',
			lang_hvt_vc: 'Spouse’s full name:',
			lang_hvt_cc: 'Full name of children:',
			lang_tuoi: 'Age:',
			lang_nn: 'Occupation:',
			lang_nlv: 'Workplace:',
			lang_trc_cm: 'What and where did he do before the August Revolution?',
			lang_trong_kc: 'What and Where did he do during the war resistance against French colony?',
			lang_den_nay: 'What and Where has he done/been since 1955 to today?(Specify name of the current employer)?',
			lang_w_hn: 'Current address:',
			lang_hdbt: 'SUMMARY OF STUDY AND WORKING',
			lang_hdbt_b: 'From..... to',
			lang_hdbt_ct: 'Work?',
			lang_hdbt_w: 'Where?',
			lang_hdbt_cv: 'Position?',
			lang_hdbt_ktkl: 'REWARDS AND DISCIPLINE',
			lang_hdbt_kt: 'Reward: ',
			lang_hdbt_kl: 'Discipline:',
			lang_cam_doan: 'UNDERTAKING',
			lang_l_cam_doan: 'I hereby undertake that all the details above are true and I will bear the full responsibility for them.',
			lang_xac_nhan: "Certification of Head of Authority, enterprise, Chairman of People's Committee of commune/ ward",
			lang_ky_ten: 'Signature of informant',
			lang_k_ght: '(Sign and write full name)',
		}
	} else if (lang == 'kr') {
		return {
			lang_chxh: '베트남 사회주의 공화국<br>독립 - 자유 - 행복',
			lang_syll: '이력서<br><i>서술문</i>',
			lang_name: '성명:',
			lang_sex: 'N남/녀:',
			lang_bir_day: '생년 월 일',
			lang_bir_month: '-',
			lang_bir_year: '-',
			lang_bir_w: '~에서',
			lang_tt_now: '등록지: ',
			lang_tt_now1: '등록지:',
			lang_cmnd: '주민등록번호:',
			lang_w_cmnd: '발급처: ',
			lang_d_cmnd: '발급년 월 일:',
			lang_m_cmnd: '-',
			lang_y_cmnd: '-',
			lang_dt_home: '연락처: 집 전화번호: ',
			lang_dt_tele: '핸드폰:',
			lang_tb: '필요 시 어디에 누구에게 소식을 통지할 수 있습니까?:',
			lang_sh: '문서번호:',
			lang_kh: '기호:',
			lang_nick_name: '가명:',
			lang_nom_name: '사용하고 있는 명: ',
			lang_qq: '본적: ',
			lang_dt: '민족: ',
			lang_tg: '종교:',
			lang_tpgd_scc: '농지개혁(이나  상공업 개혁)후의 가족의 직업',
			lang_tpbt: '현재의 본인직업: ',
			lang_tdvh: '학력: ',
			lang_language: '외국어 능력:',
			lang_tdcm: '전문 자격: ',
			lang_lhdt: '교육의 종류:',
			lang_cndt: '전공: ',
			lang_knd_d: '베트남공산당 가입일자:',
			lang_knd_w: '장소: ',
			lang_dtn_d: '호치민공산주의 청년 동맹 가입일자:',
			lang_sk: '건강상태: ',
			lang_cc: '크기:',
			lang_cn: '무게:',
			lang_nn_cm: '직업이나 전문자격: ',
			lang_capbac: '직급: ',
			lang_lchn: '기본급여: ',
			lang_nnn: '베트남인민군 입대 일자: ',
			lang_nxn: '해산일자: ',
			lang_ld_xn: '해산이유: ',
			lang_hcgd: '가족사항',
			lang_hvt_bo: '부: 성명: ',
			lang_hvt_me: '모: 성명: ',
			lang_hvt_ace: '형제자매 성명<br><i>(사람별 성명, 나이, 직업, 정치능력등 기입)</i>',
			lang_hvt_vc: '아내나 남편 성명: ',
			lang_hvt_cc: '자녀 성명:',
			lang_tuoi: '나이: ',
			lang_nn: '직무: ',
			lang_nlv: '직장',
			lang_trc_cm: '8월혁명 전에 어디서 무엇을 하십니까?',
			lang_trong_kc: '프랑스항전에 어디서 무엇을 하십니까?',
			lang_den_nay: '1955년부터 지금까지 어디서 무엇을 하십니까? (일하고 있는 회사명, 기관명등 기입한다)',
			lang_w_hn: '현주소: ',
			lang_hdbt: '본인 학습과정',
			lang_hdbt_b: '년월부터 년월까지',
			lang_hdbt_ct: '무엇을?',
			lang_hdbt_w: '어디서?',
			lang_hdbt_cv: '무슨 직업?',
			lang_hdbt_ktkl: '포상 및 징계',
			lang_hdbt_kt: '포상:',
			lang_hdbt_kl: '징계:',
			lang_cam_doan: '약속하는 말',
			lang_l_cam_doan:
				'저는 위의 내용이 사실과 틀림이 없는 것을 약정합니다. 만약 관할 당국이 나중에 부적절한 내용을 발견하면 제가 법률대로 법적 책임을 지겠습니다./.',
			lang_xac_nhan: '회사사장/ 현/면 인민위원회 확인',
			lang_ky_ten: '작성자 서명',
			lang_k_ght: '(서명 및 성명)',
		}
	} else if (lang == 'jp') {
		return {
			lang_chxh: 'ベトナム社会主義共和国<br>独立・自由・幸福',
			lang_syll: '履歴書',
			lang_name: '氏名 :',
			lang_sex: '性別 ：',
			lang_bir_day: '年生月日：',
			lang_bir_month: '-',
			lang_bir_year: '-',
			lang_bir_w: '〜で',
			lang_tt_now: '戸籍住所：',
			lang_tt_now1: '戸籍住所：',
			lang_cmnd: '身分証明書番号：',
			lang_w_cmnd: '発行機関：',
			lang_d_cmnd: '発行日：',
			lang_m_cmnd: '-',
			lang_y_cmnd: '-',
			lang_dt_home: '電話番号：　ホーム：',
			lang_dt_tele: '携帯：',
			lang_tb: '必要な時の連絡先：',
			lang_sh: '番号：',
			lang_kh: '記号：',
			lang_nick_name: '別名：',
			lang_nom_name: '通常名：',
			lang_qq: '故郷：',
			lang_dt: '民族：',
			lang_tg: '宗教: ',
			lang_tpgd_scc: '農地改革後の家族背景：',
			lang_tpbt: '現在の本人の職種：',
			lang_tdvh: '教育レベル：',
			lang_language: '外国語レベル：',
			lang_tdcm: '専門能力：',
			lang_lhdt: '教育方式：',
			lang_cndt: '専攻：',
			lang_knd_d: 'ベトナム共産党の加盟日付：',
			lang_knd_w: '加盟所：',
			lang_dtn_d: 'ホーチミン共産青年同盟の加盟日付：',
			lang_sk: '健康状態：',
			lang_cc: '身長：',
			lang_cn: '体重：',
			lang_nn_cm: '専門：',
			lang_capbac: 'レベル：',
			lang_lchn: '現在基本給：',
			lang_nnn: '入隊日：',
			lang_nxn: '復員日：',
			lang_ld_xn: '理由：',
			lang_hcgd: '家族の背景',
			lang_hvt_bo: '父親の氏名：',
			lang_hvt_me: '母親の氏名：',
			lang_hvt_ace: '兄弟、姉妹の氏名<br><i>それぞれの人の名前、年齢、住所、職種の記入</i>',
			lang_hvt_vc: '配偶者の氏名：',
			lang_hvt_cc: '子供たちの氏名：',
			lang_tuoi: '年齢：',
			lang_nn: '職種：',
			lang_nlv: '職場：',
			lang_trc_cm: '8月革命前の仕事と住所：',
			lang_trong_kc: 'フランス植民地主義に対する戦争の仕事と住所：',
			lang_den_nay: '1955年から現在までの仕事と住所（現在働いている会社名と住所の記入）：',
			lang_w_hn: '現住所：',
			lang_hdbt: '本人の学歴と職歴',
			lang_hdbt_b: '….年…..月から….<br>年…月まで',
			lang_hdbt_ct: '仕事',
			lang_hdbt_w: '場所',
			lang_hdbt_cv: '役職',
			lang_hdbt_ktkl: '表彰と叱責',
			lang_hdbt_kt: '表彰：',
			lang_hdbt_kl: '叱責：',
			lang_cam_doan: '宣言',
			lang_l_cam_doan: '上記の通り、相違ありません。相違点が発見された場合、法的処分を受けること。',
			lang_xac_nhan: '社長とか役所の所長の承認',
			lang_ky_ten: '筆記者',
			lang_k_ght: '（署名した）',
		}
	} else {
		return {
			lang_chxh: '越南社会主义共和国<br>独立 – 自由 – 幸福',
			lang_syll: '个人简历<br><i>（自述）</i>',
			lang_name: '姓名: ',
			lang_sex: '男, 女: ',
			lang_bir_day: '出生日期：',
			lang_bir_month: '-',
			lang_bir_year: '-',
			lang_bir_w: '在',
			lang_tt_now: '目前常住户口登记处: ',
			lang_tt_now1: '目前登记常住户口：',
			lang_cmnd: '身份证号：',
			lang_w_cmnd: '签发单位: ',
			lang_d_cmnd: '年',
			lang_m_cmnd: '月.',
			lang_y_cmnd: '日',
			lang_dt_home: '联系电话：家里固定电话',
			lang_dt_tele: '手机',
			lang_tb: '需要时跟谁联络？地点？',
			lang_sh: '编号:',
			lang_kh: '标记:',
			lang_nick_name: '别名:',
			lang_nom_name: '常称呼的名字: ',
			lang_qq: '籍贯: ',
			lang_dt: '民族: ',
			lang_tg: '宗教:',
			lang_tpgd_scc: '田地改革后的家庭成分（或工商业改造）：',
			lang_tpbt: '目前本人状况：',
			lang_tdvh: '文化水平：',
			lang_language: '外语:',
			lang_tdcm: '任职资格：',
			lang_lhdt: '培训类型：',
			lang_cndt: '专门培训：',
			lang_knd_d: '加入越南共产党于',
			lang_knd_w: '加入地点',
			lang_dtn_d: '加入胡志明共产党青年团',
			lang_sk: '目前身体状况',
			lang_cc: '身高 ',
			lang_cn: '体重:',
			lang_nn_cm: '职业或专业水平: ',
			lang_capbac: '级别：',
			lang_lchn: '目前薪水：',
			lang_nnn: '加入越南人民军队（前进年青人）：',
			lang_nxn: '出队日期：',
			lang_ld_xn: '理由: ',
			lang_hcgd: '家庭环境',
			lang_hvt_bo: '父亲姓名',
			lang_hvt_me: '母亲姓名：',
			lang_hvt_ace: '亲兄弟姐妹的姓名<br><i>（注明每个人的姓名、年龄、住址、职业和政治水平）</i>',
			lang_hvt_vc: '老婆或老公的姓名',
			lang_hvt_cc: '孩子的姓名：',
			lang_tuoi: '年龄: ',
			lang_nn: '行业 :',
			lang_nlv: '工作地点',
			lang_trc_cm: '八月革命前在哪工作？地点？',
			lang_trong_kc: '法国殖民地抗战中在哪工作？地点？',
			lang_den_nay: '从1955年到目前在哪工作？地点？（注明目前正在工作的机关、企业的名称）',
			lang_w_hn: '目前住址：',
			lang_hdbt: '本人的活动过程',
			lang_hdbt_b: '从   年    月<br>至年    月',
			lang_hdbt_ct: '工作？',
			lang_hdbt_w: '地点？',
			lang_hdbt_cv: '职务？',
			lang_hdbt_ktkl: '奖励和纪律',
			lang_hdbt_kt: '奖励 : ',
			lang_hdbt_kl: '纪律 : ',
			lang_cam_doan: '承诺言',
			lang_l_cam_doan: '我承诺上述所写是属实并对自述内容承担责任，若后主管机关发现有谎报我将承担全部法律责任./.',
			lang_xac_nhan: '机关和企业领导、社坊人民委员会主席的确认',
			lang_ky_ten: '报者',
			lang_k_ght: '(签名)',
		}
	}
}
