export const resin4Don = {
    "data": {
        "result": true,
        "message": "Lấy CV thành công",
        "data": {
            "_id": 745,
            "name": "CV du lịch 5",
            "alias": "thiet-ke-chuyen-nghiep/cv-du-lich-5",
            "url_alias": "du-lich/mau-05",
            "url_canonical": "",
            "image": "cv_745.jpg",
            "price": 0,
            "colors": "23570e,fb0522,0868f8,999222",
            "view": 835,
            "love": 4,
            "download": 686,
            "vip": 1,
            "cv_index": 0,
            "cid": 3,
            "content": "",
            "mota_cv": "",
            "html_vi": "{\"css\":{\"color\":\"23570e\",\"font\":\"Roboto\",\"font_size\":\"normal\",\"font_spacing\":\"normal\"},\"cv_title\":\"CV du lịch\",\"avatar\":\"images/no_avatar.jpg\",\"name\":\"Nguyễn Đăng Nam\",\"position\":\"QUẢN LÝ TOUR DU LỊCH\",\"introduction\":\"\",\"menu\":[{\"id\":\"box01\",\"order\":1,\"content\":{\"title\":\"\",\"content\":{\"type\":\"profile\",\"content\":{\"birthday\":\"21/05/1995\",\"sex\":\"Nam\",\"phone\":\"0123456789\",\"email\":\"test@gmail.com\",\"address\":\"Số 1 đường Cầu Giấy\",\"face\":\"\"}}},\"status\":\"\"},{\"id\":\"box02\",\"order\":2,\"content\":{\"title\":\"MỤC TIÊU NGHỀ NGHIỆP\",\"content\":\"\\n                                    \\n                                    Học hỏi, tích lũy thêm nhiều kinh nghiệm việc làm trong ngành du lịch, tham gia vào nhiều dự án quan trọng phát triển Công ty.<br>Mong muốn đảm nhận vị trí quản lý các tour du lịch tại Công ty. Mục tiêu sau 3 năm cống hiến sẽ giữ vị trí Quản lý điều hành du lịch. <br> \"},\"status\":\"\"},{\"id\":\"box03\",\"order\":3,\"content\":{\"title\":\"KỸ NĂNG\",\"content\":{\"type\":\"skill\",\"skills\":[{\"name\":\"Kỹ năng giao tiếp và thương lượng tốt\",\"exp\":\"50\"},{\"name\":\"Khả năng tiếng Anh tốt\",\"exp\":\"80\"},{\"name\":\"Kỹ năng làm việc nhóm hiệu quả\",\"exp\":\"80\"}]}},\"status\":\"\"},{\"id\":\"box04\",\"order\":4,\"content\":{\"title\":\"GIẢI THƯỞNG\",\"content\":\"- Nhân viên tích cực nhất tại Công ty Du lịch CV365.<br>- Tình nguyện viên nhiệt tình nhất tại Câu lạc bộ Du lịch – Hành trình kết nối 365.<br>- Sinh viên giỏi tại trường Đại học Ngoại Thương.<br> \"},\"status\":\"\"},{\"id\":\"box05\",\"order\":5,\"content\":{\"title\":\"CHỨNG CHỈ\",\"content\":\"- Chứng chỉ Khóa học Lãnh đạo tài ba tại Trung tâm kỹ năng giao tiếp CV365<br>- Chứng chỉ ngoại ngữ TOIEC 3.7/4<br>- Chứng chỉ tin học văn phòng<br>\"},\"status\":\"\"},{\"id\":\"box06\",\"order\":6,\"content\":{\"title\":\"SỞ THÍCH\",\"content\":\"-\\tĐi du lịch<br>-\\tXem phim<br>-\\tNghe nhạc<br>\"},\"status\":\"\"},{\"id\":\"box07\",\"order\":7,\"content\":{\"title\":\"NGƯỜI THAM CHIẾU\",\"content\":\" Lê Trọng Tín<br>Giám đốc điều hành tour tại Công ty CV365<br>Số điện thoại: 0978 532 148 \"},\"status\":\"\"}],\"experiences\":[{\"id\":\"block01\",\"order\":1,\"content\":{\"title\":\"TRÌNH ĐỘ HỌC VẤN\",\"content\":[{\"title\":\"Đại học Ngoại Thương\",\"date\":\"\",\"subtitle\":\"Cử nhân Khoa Du lịch\",\"content\":\" Tốt nghiệp loại giỏi\"}]},\"status\":\"\"},{\"id\":\"block02\",\"order\":2,\"content\":{\"title\":\"KINH NGHIỆM LÀM VIỆC\",\"content\":[{\"title\":\"Công ty Du lịch CV365\",\"date\":\"\",\"subtitle\":\"Vị trí: Trưởng phòng tổ chức du lịch kết hợp hội thảo\",\"content\":\"- Liên lạc, đàm phán hợp đồng với các công ty tổ chức hội thảo hội nghị, các công ty nước ngoài.<br> - Tổ chức các cuộc họp, buổi hội thảo cho công ty nước ngoài ở Việt Nam.<br>- Lên kế hoạch cho các tour du lịch cả trong và ngoài nước cho khách.<br>- Cung cấp thông tin về các tour cho khách.<br>- Đào tạo nhân viên mới, quản lý đội ngũ nhân viên tại văn phòng.<br>- Giám sát, đánh giá năng lực làm việc của nhân viên theo định kỳ hàng tháng.<br>\"},{\"title\":\"Đại lý vé máy bay CV365\",\"date\":\"\",\"subtitle\":\"Vị trí: Nhân viên kinh doanh tại phòng vé\",\"content\":\"- Chuẩn bị hợp đồng cho các dịch vụ đặt vé, dịch vụ hàng không cho khách hàng.<br> - Liên lạc với khách để trao đổi về hợp đồng.<br>- Cập nhật thông tin vé máy bay mới nhất cho khách hàng.<br>- Tổng hợp, báo cáo tình hình kinh doanh cho Ban Giám đốc. <br>- Thu tiền từ khách, chuẩn bị hóa đơn bán hàng theo tháng.<br>\"}]},\"status\":\"\"},{\"id\":\"block03\",\"order\":3,\"content\":{\"title\":\"HOẠT ĐỘNG\",\"content\":[{\"title\":\"Đội viên tại Đội thanh niên Xung kích trường Đại học Ngoại Thương\",\"date\":\"\",\"subtitle\":\"Tình nguyện viên\",\"content\":\"- Tham gia Hiến máu nhân đạo hàng năm được tổ chức tại Đội máu Quốc gia Thành phố Hà Nội<br> - Là thành viên của Câu lạc bộ Du lịch – Hành trình kết nối 365 <br>\"}]},\"status\":\"\"},{\"id\":\"block04\",\"order\":4,\"content\":{\"title\":\"DỰ ÁN THAM GIA\",\"content\":[{\"title\":\"Dự án Du lịch xanh Thành phố Hà Nội tại Công ty Du lịch CV365\",\"date\":\"\",\"subtitle\":\"Vai trò đảm nhiệm: Lập kế hoạch lên các tour du lịch tham quan và bảo vệ môi trường trong phạm vi Thành phố Hà Nội.\",\"content\":\"Mục đích của dự án: Góp phần hình thành ý thức cho người dân bảo vệ môi trường thành phố, từ đó tạo hình ảnh đẹp cho các địa điểm du lịch tại Hà Nội. Kết quả: Nâng cao số khách hàng đăng ký Tour du lịch tại Công ty Du lịch CV365.<br>\"}]},\"status\":\"\"},{\"id\":\"block05\",\"order\":5,\"content\":{\"title\":\"THÔNG TIN THÊM\",\"content\":[{\"title\":\"Đại học CV365\",\"date\":\"\",\"subtitle\":\"Thêm những thông tin khác ( nếu cần )\",\"content\":\"\"}]},\"status\":\"\"}]}",
            "html_en": "{\"css\":{\"color\":\"23570e\",\"font\":\"Roboto\",\"font_size\":\"normal\",\"font_spacing\":\"normal\"},\"cv_title\":\"CV du lịch\",\"avatar\":\"images/no_avatar.jpg\",\"name\":\"Nguyen Dang Nam\",\"position\":\"RECRUITMENT CONSULTANT\",\"introduction\":\"\",\"menu\":[{\"id\":\"box01\",\"order\":1,\"content\":{\"title\":\"\",\"content\":{\"type\":\"profile\",\"content\":{\"birthday\":\"19/05/1995\",\"sex\":\"male\",\"phone\":\"098567567567\",\"email\":\"test@gmail.com\",\"address\":\"No.1, Cau Giay Street\",\"face\":\"\"}}},\"status\":\"\"},{\"id\":\"box02\",\"order\":2,\"content\":{\"title\":\"CAREER GOALS\",\"content\":\"\\n  Learning, accumulating more working experience in the tourism industry, participating in many important projects to develop the Company <br>I look forward to taking the position of tour manager at the Company. The goal after 3 years of dedication is the position of Tourism Executive Manager.<br>\"},\"status\":\"\"},{\"id\":\"box03\",\"order\":3,\"content\":{\"title\":\"PERSONAL SKILLS\",\"content\":{\"type\":\"skill\",\"skills\":[{\"name\":\"Good communication and negotiation skills\",\"exp\":\"50\"},{\"name\":\"Ability to work in high pressure environment\",\"exp\":\"80\"},{\"name\":\"Good English ability\",\"exp\":\"80\"}]}},\"status\":\"\"},{\"id\":\"box04\",\"order\":4,\"content\":{\"title\":\"AWARDS \",\"content\":\"- The most active staff at CV365 Tourism Company.<br>- The most enthusiastic volunteer at the Travel Club - Connection journey 365<br>- Excellent student at Foreign Trade University<br> \"},\"status\":\"\"},{\"id\":\"box05\",\"order\":5,\"content\":{\"title\":\"CERTIFICATES\",\"content\":\"- Talented Leadership Course Certificate at CV365 Communication Skills Center<br>- TOIEC 3.7 / 4 foreign language certificate<br>- Office computing certificate<br> \"},\"status\":\"\"},{\"id\":\"box06\",\"order\":6,\"content\":{\"title\":\"Hobbies \",\"content\":\"- Traveling<br>- Watching movie<br>- Listening to music<br>\"},\"status\":\"\"},{\"id\":\"box07\",\"order\":7,\"content\":{\"title\":\"References \",\"content\":\"Le Trong Tin<br>Tour executive manager at CV365 Company<br>Phone number: 0978 532 148<br>\"},\"status\":\"\"}],\"experiences\":[{\"id\":\"block01\",\"order\":1,\"content\":{\"title\":\"EDUCATION\",\"content\":[{\"title\":\"Foreign Trade University\",\"date\":\"\",\"subtitle\":\"Bachelor of Tourism\",\"content\":\"\\n  Classification: Distinction                                    \"}]},\"status\":\"\"},{\"id\":\"block02\",\"order\":2,\"content\":{\"title\":\"WORKING EXPERIENCE\",\"content\":[{\"title\":\"CV365 Tourism Company\",\"date\":\"\",\"subtitle\":\"Position: Head of Tourism Organization and Conference\",\"content\":\"- Contacting, negotiating contracts with companies organizing seminars, conferences, foreign companies.<br> - Organizing meetings and seminars for foreign companies in Vietnam.<br>- Planning tours both at home and abroad for customers<br>- Providing information about tours for customers<br>- Training new employees, managing staff at the office.<br>- Supervising and evaluating employees' working capacity monthly<br>\"},{\"title\":\"Airline ticket agent CV365\",\"date\":\"\",\"subtitle\":\"Position: Sales staff at the ticket office\",\"content\":\"- Preparing contracts for ticketing services, aviation services for customers.<br> - Contacting the customer to discuss the contract.<br>- Updating the latest airline ticket information for customers<br>- Summarizing and reporting on the business situation to the Board of Directors.<br>- Collecting money from customers, preparing sales invoices by month<br>\"}]},\"status\":\"\"},{\"id\":\"block03\",\"order\":3,\"content\":{\"title\":\"ACTIVITIES\",\"content\":[{\"title\":\"Volunteer Group - Green Summer: \\\"Summer of Love\\\"\",\"date\":\"\",\"subtitle\":\"Volunteer (09/2013 - 08/2014)\",\"content\":\"\\n  - Supporting to build a new house for a poor household in the commune<br>- Organizing summer activities for local children during volunteering.<br> \"}]},\"status\":\"\"},{\"id\":\"block04\",\"order\":4,\"content\":{\"title\":\"PROJECT PARTICIPATION\",\"content\":[{\"title\":\"Green Tourism Project in Hanoi City at CV365 Tourism Company\",\"date\":\"\",\"subtitle\":\"Role: Planning on sightseeing tours and environmental protection within Hanoi City.\",\"content\":\"\\n  The purpose of the project: Contributing to forming consciousness for people to protect the city environment, thereby creating a beautiful image for tourist sites in Hanoi. Result: Increasing the number of customers registered Tour at CV365 Tourism Company.<br>\"}]},\"status\":\"\"},{\"id\":\"block05\",\"order\":5,\"content\":{\"title\":\"Further information\",\"content\":[{\"title\":\"\",\"date\":\"\",\"subtitle\":\"Add other information (if needed):\",\"content\":\"\\n \"}]},\"status\":\"\"}]}",
            "html_jp": "{\"css\":{\"color\":\"23570e\",\"font\":\"sun-exta\",\"font_size\":\"normal\",\"font_spacing\":\"normal\"},\"cv_title\":\"CV du lịch\",\"avatar\":\"images/no_avatar.jpg\",\"name\":\"NGUYEN DANG NAM\",\"position\":\"旅程管理者\",\"introduction\":\"\",\"menu\":[{\"id\":\"box01\",\"order\":1,\"content\":{\"title\":\"\",\"content\":{\"type\":\"profile\",\"content\":{\"birthday\":\"19/05/1992\",\"sex\":\"男性の\",\"phone\":\"098567567567\",\"email\":\"test@gmail.com\",\"address\":\"カウジエイ通り1号\",\"face\":\"\"}}},\"status\":\"\"},{\"id\":\"box02\",\"order\":2,\"content\":{\"title\":\"業務目標\",\"content\":\"観光業界での職業上の学び,　経験蓄積をすること <br>及び会社を発展させるために多くの重要なプロジェクトに参加することを目的としています。<br>当社の旅程管理者として働きたいことです。3年後の献身的な努力の目標は　旅程管理主任者の地位を築くことが出来ます。<br> \"},\"status\":\"\"},{\"id\":\"box03\",\"order\":3,\"content\":{\"title\":\"スキル\",\"content\":{\"type\":\"skill\",\"skills\":[{\"name\":\"交渉力スキル、コミュニケーションスキルは優れていえます\",\"exp\":\"50\"},{\"name\":\"指導力に優れた \",\"exp\":\"80\"},{\"name\":\"チームワークを効果的に活用する \",\"exp\":\"80\"}]}},\"status\":\"\"},{\"id\":\"box04\",\"order\":4,\"content\":{\"title\":\"表彰\",\"content\":\"- CV365観光会社の優良スタッフ表彰<br>- 旅行クラブ– 365つながる 旅の熱心なボランティアを顕彰<br>- 外国貿易大学の優秀な学生といわれる資格があった<br> \"},\"status\":\"\"},{\"id\":\"box05\",\"order\":5,\"content\":{\"title\":\"証明書\",\"content\":\"- CV365コミュニケーションスキルセンターで優秀なリーダーシップコースの資格<br>- TOIEC 3.7 / 4外国語認証<br>- コンピュータサイエンス 学位<br>\"},\"status\":\"\"},{\"id\":\"box06\",\"order\":6,\"content\":{\"title\":\"趣味\",\"content\":\"- 旅行<br>- 映画を見ること<br>- 音楽を聴くこと<br>\"},\"status\":\"\"},{\"id\":\"box07\",\"order\":7,\"content\":{\"title\":\"連絡先\",\"content\":\"\\n  Mr.Le Trong Tin<br>CV365会社のツアーの最高経営責任者<br>電話番号：0978 532 148  \"},\"status\":\"\"}],\"experiences\":[{\"id\":\"block01\",\"order\":1,\"content\":{\"title\":\"学歴\",\"content\":[{\"title\":\"外国貿易大学\",\"date\":\"\",\"subtitle\":\"観光の学士号\",\"content\":\"\\n 卒業レベル：良\\n   \"}]},\"status\":\"\"},{\"id\":\"block02\",\"order\":2,\"content\":{\"title\":\"職歴\",\"content\":[{\"title\":\"CV365旅行会社\",\"date\":\"\",\"subtitle\":\"位地：観光兼会議開催部長\",\"content\":\"- 会議を開催している企業、外国企業との連絡、契約交渉<br> - ベトナムにおいて外国企業のための会議やセミナーを開催する。<br>- 顧客向けの国内・海外旅行を計画します<br>- 顧客にツアーに関する情報を提供します<br>- 新入社員の教育、管理事務所スタッフの管理業務が含まれます<br>- 毎月従業員の作業能力を評価します。<br>\"},{\"title\":\"航空券販売代理店\",\"date\":\"\",\"subtitle\":\"職位：営業スタッフ\",\"content\":\"- 顧客向けの発券サービス、航空サービスの契約を準備する<br>- 契約について話し合うために顧客に連絡する<br>- 最新の航空券情報を更新して顧客に通知する。<br>- 事業の状況について要約し、取締役会に報告する<br>- 顧客からお金を集め、月ごとに売上請求書を作成する。<br>\"}]},\"status\":\"\"},{\"id\":\"block03\",\"order\":3,\"content\":{\"title\":\"活動\",\"content\":[{\"title\":\"- 外国貿易大学の待ち伏せ青少年グループのメンバー。\",\"date\":\"\",\"subtitle\":\"- ハノイ国立血液チームで開催される毎年恒例の献血に参加します。\",\"content\":\"- 旅行クラブ– 365つながる 旅のメンバー。<br>\"}]},\"status\":\"\"},{\"id\":\"block04\",\"order\":4,\"content\":{\"title\":\"参加プロジェクト\",\"content\":[{\"title\":\"CV365旅行会社のハノイ市グリーン・ツーリズムプロジェクト\",\"date\":\"\",\"subtitle\":\"担当内容：ハノイ市内の観光ツアーと環境保護の計画を立てる。\",\"content\":\"\\n   プロジェクトの目的：人々が都市環境を守るための意識を形成することに貢献し、それによってハノイの観光地のための美しいイメージを作成します。<br> 結果：CV365観光会社でのツアーを予約する顧客数を増やす<br>\"}]},\"status\":\"\"},{\"id\":\"block05\",\"order\":5,\"content\":{\"title\":\"追加情報\",\"content\":[{\"title\":\"\",\"date\":\"\",\"subtitle\":\"その他情報（必要の場合）\",\"content\":\"\\n  \"}]},\"status\":\"\"}]}",
            "html_cn": "{\"css\":{\"color\":\"23570e\",\"font\":\"sun-exta\",\"font_size\":\"normal\",\"font_spacing\":\"normal\"},\"cv_title\":\"CV du lịch\",\"avatar\":\"images/no_avatar.jpg\",\"name\":\"阮灯南\",\"position\":\"旅游管理者\",\"introduction\":\"\",\"menu\":[{\"id\":\"box01\",\"order\":1,\"content\":{\"title\":\"\",\"content\":{\"type\":\"profile\",\"content\":{\"birthday\":\"21/05/1995\",\"sex\":\"南\",\"phone\":\"098567567567\",\"email\":\"test@gmail.com\",\"address\":\"河内、纸桥\",\"face\":\"\"}}},\"status\":\"\"},{\"id\":\"box02\",\"order\":2,\"content\":{\"title\":\"事业目标\",\"content\":\"学习、累计旅游行业之工作经验，参加更多发展公司之重要项目<br>希望担任公司之旅游管理位置。三年后之目标是担任旅游调度管理位置<br>\"},\"status\":\"\"},{\"id\":\"box03\",\"order\":3,\"content\":{\"title\":\"技能\",\"content\":{\"type\":\"skill\",\"skills\":[{\"name\":\"交际和商讨技能好\",\"exp\":\"50\"},{\"name\":\"能在高压力环境工作\",\"exp\":\"80\"},{\"name\":\"英语能力好\",\"exp\":\"80\"}]}},\"status\":\"\"},{\"id\":\"box04\",\"order\":4,\"content\":{\"title\":\"奖项\",\"content\":\"CV365旅游公司之最积极员工<br>365联合行程-旅游俱乐部之最热情志愿员<br>外贸大学之优秀学生<br>\"},\"status\":\"\"},{\"id\":\"box05\",\"order\":5,\"content\":{\"title\":\"凭证\",\"content\":\"由CV365交际技能中心举办之才干领导学期证书<br>TOIEC 3.7/4外语证书<br>办公电脑证书<br>\"},\"status\":\"\"},{\"id\":\"box06\",\"order\":6,\"content\":{\"title\":\"爱好\",\"content\":\"\\n  旅游<br>看电影<br>听音乐<br>\"},\"status\":\"\"},{\"id\":\"box07\",\"order\":7,\"content\":{\"title\":\"确认者\",\"content\":\"\\n 黎仲信<br>CV365公司之旅游调度经理<br>电话号码：0978 532 148 \"},\"status\":\"\"}],\"experiences\":[{\"id\":\"block01\",\"order\":1,\"content\":{\"title\":\"学习水平\",\"content\":[{\"title\":\"外贸大学\",\"date\":\"\",\"subtitle\":\"旅游系本科\",\"content\":\"\\n 优秀之毕业成绩 \"}]},\"status\":\"\"},{\"id\":\"block02\",\"order\":2,\"content\":{\"title\":\"工作经验\",\"content\":[{\"title\":\"CV365旅游公司\",\"date\":\"\",\"subtitle\":\"职务：旅游组织配合举办会议之课长\",\"content\":\"与举办会议之公司、外国公司联系、商讨合同<br> 给外国公司在越南举办会议<br>给客户设计国内和国外之旅游计划<br>给客户提供旅游信息<br>培训新员工、管理在办公室之员工队伍<br>监督并月定期评估员工之工作能力<br>\"},{\"title\":\"CV365机票代理\",\"date\":\"\",\"subtitle\":\"职务：销售员\",\"content\":\"给客户之航空、订票等服务准备合同<br> 与客户联系沟通合同事宜<br>给客户收集最新之信息<br>把经营情况汇总并报告经理会<br>从客户那收回金额，准备月发票<br>\"}]},\"status\":\"\"},{\"id\":\"block03\",\"order\":3,\"content\":{\"title\":\"活动\",\"content\":[{\"title\":\"外贸大学之突击青年队之队员\",\"date\":\"\",\"subtitle\":\"每年参加在河内市国家血团举办之志愿献血活动\",\"content\":\"365联合行程-旅游俱乐部之成员\"}]},\"status\":\"\"},{\"id\":\"block04\",\"order\":4,\"content\":{\"title\":\"参与的活动\",\"content\":[{\"title\":\"CV365旅游公司之河内市绿化旅游预案\",\"date\":\"\",\"subtitle\":\"担任角色：给河内市范围内之旅游参观及环保活动设立计划\",\"content\":\"\\n 预案目的：出力给居民形成环保意识从而给河内旅游地点创出美好形象<br>  结果：提升在CV365旅游公司登记旅游之客户数量<br>\"}]},\"status\":\"\"},{\"id\":\"block05\",\"order\":5,\"content\":{\"title\":\"其他信息\",\"content\":[{\"title\":\"补充其他信息（若需要）\",\"date\":\"\",\"subtitle\":\"\",\"content\":\"\\n  \"}]},\"status\":\"\"}]}",
            "html_kr": "{\"css\":{\"color\":\"23570e\",\"font\":\"sun-exta\",\"font_size\":\"normal\",\"font_spacing\":\"normal\"},\"cv_title\":\"CV du lịch\",\"avatar\":\"images/no_avatar.jpg\",\"name\":\"응웬당남\",\"position\":\"여행 투어 관리자\",\"introduction\":\"\",\"menu\":[{\"id\":\"box01\",\"order\":1,\"content\":{\"title\":\"\",\"content\":{\"type\":\"profile\",\"content\":{\"birthday\":\"19/05/1992\",\"sex\":\"여성\",\"phone\":\"098567567567\",\"email\":\"test@gmail.com\",\"address\":\"Cau Giay로 1호\",\"face\":\"\"}}},\"status\":\"\"},{\"id\":\"box02\",\"order\":2,\"content\":{\"title\":\"직업의 목표\",\"content\":\"관광사업에서 배우고 경험을 더 많이 쌓고 회사를 발전하는 많은 중요한 프로젝트에 참여한다.<br>회사에서 투어 관리직을 맡아보는 것을 원한다. 목표는 3년동안 일하고 회사에 헌신한 후에 여행 운영관리직을 차지하는 것이다.<br>  \"},\"status\":\"\"},{\"id\":\"box03\",\"order\":3,\"content\":{\"title\":\"기능\",\"content\":{\"type\":\"skill\",\"skills\":[{\"name\":\"좋은 의사소통 및 협상 기술.\",\"exp\":\"50\"},{\"name\":\"훌륭한 지도력.\",\"exp\":\"80\"},{\"name\":\"효과적인 팀워크 기술.\",\"exp\":\"80\"}]}},\"status\":\"\"},{\"id\":\"box04\",\"order\":4,\"content\":{\"title\":\"상금\",\"content\":\"- CV365 관광 기업에서 제일 적극적인 인원.<br>- 365 관광–연결여정 클럽에서 제일 열정적인 자원 봉사자.<br>- 외상대학교에서 훌륭한 대학생.<br>\"},\"status\":\"\"},{\"id\":\"box05\",\"order\":5,\"content\":{\"title\":\"자격증\",\"content\":\"- CV365의사소통 기술 센터에서 대단한 리더십 코스의 인증<br>- 외국어 증명서: 토익3.7/4<br>- 사무실 컴퓨터 증명서<br>\"},\"status\":\"\"},{\"id\":\"box06\",\"order\":6,\"content\":{\"title\":\"취미\",\"content\":\"\\n - 독서<br>- 영화 보기<br>- 사진 찍기<br>- 자원봉사  \"},\"status\":\"\"},{\"id\":\"box07\",\"order\":7,\"content\":{\"title\":\"참고자\",\"content\":\"\\n \\t레 트롱 틴<br>CV365 회사의 투어 임원<br>연락처: 0978 532 148<br>\"},\"status\":\"\"}],\"experiences\":[{\"id\":\"block01\",\"order\":1,\"content\":{\"title\":\"교육수준\",\"content\":[{\"title\":\"외상대학교\",\"date\":\"\",\"subtitle\":\"\\t관광학사\",\"content\":\"\\n 우등으로 졸업했음\\n \"}]},\"status\":\"\"},{\"id\":\"block02\",\"order\":2,\"content\":{\"title\":\"경력\",\"content\":[{\"title\":\"CV365 여행 회사\",\"date\":\"\",\"subtitle\":\"직위: 관광 및 컨퍼런스 조직부장 \",\"content\":\"- 컨퍼런스 및 회의 개최는 기업이나 해외 기업와 연락하고  계약 협상함.- 베트남에 있는 외국 기업을 위해 컨퍼런스 및 회의 개최함.<br>- 고객을 위해 국내외 여행 투어 계획을 세움.<br>- 고객을 위해 투어에 대한 정보를 공급.<br>- 신입 교육 및 사무직원 관리.<br>- 매월 정기적으로 직원의 근무 능력을 감독하고 평가함.<br>\"},{\"title\":\"항공 티켓 대행사\",\"date\":\"\",\"subtitle\":\"직위: 매표소의 영업사원\",\"content\":\"- 고객을 위해 표예약 서비스 및 항공 서비스에 대한 계약을 준비.<br> - 계약을 논의하기 위해 고객에게 문의.<br>- 고객을 위해 최신 항공권 정보를 업데이트.<br>- 비즈니스 상황을 요약하고 경영진에게 보고해줌.<br>- 고객에서 수금하고 월별 판매 송장을 준비.<br>\"}]},\"status\":\"\"},{\"id\":\"block03\",\"order\":3,\"content\":{\"title\":\"교내 활동\",\"content\":[{\"title\":\"- 외상대학교에서 충격 청년대의 대원\",\"date\":\"\",\"subtitle\":\"- 매년 하노이시 전국 혈액팀에서 열리는 헌혈 행사에 참여\",\"content\":\"- 365 관광–연결여정 클럽의 멤버.\"}]},\"status\":\"\"},{\"id\":\"block04\",\"order\":4,\"content\":{\"title\":\"참가 프로젝트\",\"content\":[{\"title\":\"CV365 관광 기업에서 하노이시티 그린 투어리즘 피로젝트\",\"date\":\"\",\"subtitle\":\"담당한 역할: 히노이에서 관광 투어 및 환경 보호 계획 작성.\",\"content\":\"\\n 프로젝트 목적: 도시환경을 보호하자는 시민의식을 만들어 여행지로써의 하노이를 최고의 이미지로 만드는 것이다.<br> 결과: CV365 관광 기업에서 관광 투어를 등록하는 고객수를 향상시킨 것이다.<br>\"}]},\"status\":\"\"},{\"id\":\"block05\",\"order\":5,\"content\":{\"title\":\"추가정보\",\"content\":[{\"title\":\"기타 정보( 필요시)\",\"date\":\"\",\"subtitle\":\"\",\"content\":\"\\n  \"}]},\"status\":\"\"}]}",
            "cate_id": 65,
            "lang_id": 0,
            "design_id": 2,
            "exp": 0,
            "nhucau": 0,
            "meta_title": "",
            "meta_key": "",
            "meta_des": "",
            "thutu": 0,
            "full": "#cv-main,#cv-content",
            "status": 1,
            "cv_point": 1463,
            "type": 0
        }
    },
    "error": null
}
export const dataDonMau = {
    "data": {
        "result": true,
        "message": "Danh sách đơn theo ngành",
        "cate": [
            {
                "_id": 9,
                "name": "Bất Động Sản",
                "alias": "bat-dong-san",
                "meta_h1": "Đơn Xin Việc Bất Động Sản",
                "content": "<p dir=\"ltr\" style=\"text-align: justify;\"><em><span style=\"font-size:14px;\">Nếu bạn đang trong tư thế người t&igrave;m việc, chắc hẳn đơn xin việc đ&atilde; l&agrave; một &ldquo;thủ tục&rdquo; kh&ocirc;ng c&ograve;n qu&aacute; xa lạ. Tuy nhi&ecirc;n, nếu bạn đang muốn ứng tuyển v&agrave;o c&ocirc;ng việc thuộc lĩnh vực bất động sản, vậy l&agrave;m thế n&agrave;o để bạn c&oacute; thể tạo ra một mẫu <strong>đơn xin việc bất động sản</strong> nhỉ? Hẳn l&agrave;, đơn xin việc ng&agrave;nh bất động sản sẽ kh&aacute;c biệt một ch&uacute;t so với c&aacute;c mẫu đơn xin việc th&ocirc;ng thường hay c&aacute;c mẫu đơn xin việc theo ng&agrave;nh nghề kh&aacute;c. Để biết th&ecirc;m chi tiết về việc l&agrave;m c&aacute;ch n&agrave;o để c&oacute; một đơn xin việc &ldquo;đốn tim&rdquo; nh&agrave; tuyển dụng ngay lần đầu ti&ecirc;n, mời bạn đọc theo d&otilde;i nội dung b&agrave;i viết sau đ&acirc;y!</span></em></p>\n\n<h2 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">1. Tầm quan trọng của đơn xin việc ng&agrave;nh bất động sản&nbsp;</span></h2>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Bạn biết đấy, nếu để n&oacute;i ra một c&aacute;i t&ecirc;n cho một lĩnh vực &ldquo;đỉnh cao&rdquo; nhất hiện nay, th&igrave; chắc chắn vị tr&iacute; số một thuộc về ng&agrave;nh bất động sản. Trong một thị trường địa ốc nhộn nhịp v&agrave; ng&agrave;y c&agrave;ng triển vọng như thế, những cơ hội về việc l&agrave;m sẽ c&agrave;ng mở rộng cho c&aacute;c lao động Việt Nam. Đặc biệt l&agrave; c&aacute;c bạn trẻ đam m&ecirc; kinh doanh, am hiểu thị trường v&agrave; c&oacute; một sự chuy&ecirc;n nghiệp kh&ocirc;ng hề nhỏ trong qu&aacute; tr&igrave;nh giao tiếp v&agrave; chinh phục kh&aacute;ch h&agrave;ng. Tuy nhi&ecirc;n, bạn c&oacute; thể bị &ldquo;đ&aacute;nh trượt&rdquo; bất cứ l&uacute;c n&agrave;o nếu chẳng may, bạn sở hữu một l&aacute; đơn xin việc ng&agrave;nh bất động sản kh&ocirc;ng ph&ugrave; hợp, kh&ocirc;ng ấn tượng v&agrave; kh&ocirc;ng đẹp.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\"><strong>Đơn xin việc ng&agrave;nh bất động sản</strong> - Kh&ocirc;ng chỉ ng&agrave;nh bất động sản, c&aacute;c l&aacute;&nbsp;<a href=\"https://timviec365.vn/cv365/don-xin-viec-kien-truc\"><strong>đơn xin việc kiến tr&uacute;c</strong></a>, <a href=\"https://timviec365.vn/cv365/don-xin-viec-tiep-thi-quang-cao\"><strong>đơn xin việc tiếp thị quảng c&aacute;o</strong></a> hay <a href=\"https://timviec365.vn/cv365/don-xin-viec-thuong-mai-dien-tu\"><strong>đơn xin việc thương mại điện tử</strong></a>, ...&nbsp;đang bị c&aacute;c ứng vi&ecirc;n &ldquo;xem nhẹ&rdquo;. Nhưng bạn biết kh&ocirc;ng? Nếu như&nbsp;CV xin việc l&agrave; một &ldquo;c&ocirc;ng cụ&rdquo; kh&ocirc;ng thể đắc lực hơn để bạn sử dụng chiến đấu với c&aacute;c nh&agrave; tuyển dụng tr&ecirc;n chiến tuyến, th&igrave; đơn xin việc ch&iacute;nh l&agrave; một &ldquo;hậu phương&rdquo;, n&oacute; c&oacute; thể l&agrave; &ldquo;linh hồn&rdquo; của một bộ hồ sơ ứng vi&ecirc;n.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-tầm quan trọng\" height=\"600\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/tam-quan-trong-cua-don-xin-viec-bat-dong-san(1).jpg\" width=\"800\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Khi bạn bắt đầu một h&agrave;nh tr&igrave;nh chinh phục ước mơ trở th&agrave;nh một chuy&ecirc;n vi&ecirc;n kinh doanh ng&agrave;nh bất động sản, th&igrave; việc viết một l&aacute; đơn xin việc l&agrave; rất quan trọng. Đơn xin việc bất động sản kh&aacute;c với CV xin việc bất động sản ở chỗ, nếu như CV của bạn nhấn mạnh nhiều về tr&igrave;nh độ hay kinh nghiệm từng trải th&igrave; đơn xin việc l&agrave; nhẹ nh&agrave;ng v&agrave; bay bổng hơn, n&oacute; thể hiện được những thế mạnh của bạn, v&agrave; đương nhi&ecirc;n những thế mạnh đ&oacute; rất ph&ugrave; hợp với y&ecirc;u cầu để trở th&agrave;nh một chuy&ecirc;n vi&ecirc;n kinh doanh bất động sản. N&oacute;i như vậy để thấy rằng, một l&aacute; đơn xin việc ng&agrave;nh bất động sản sẽ gi&uacute;p bạn &ldquo;quảng b&aacute;&rdquo; được h&igrave;nh ảnh của bản th&acirc;n, l&agrave;m nổi bật l&ecirc;n những ưu điểm cũng như những mong muốn tha thiết được nhận v&agrave;o l&agrave;m việc của bạn.V&agrave; hơn hết, một đơn xin việc bất động sản được đầu tư một c&aacute;ch c&oacute; t&acirc;m huyết, n&oacute; sẽ gi&uacute;p cho nh&agrave; tuyển dụng nhận ra bạn t&ocirc;n trọng v&agrave; mong muốn hợp t&aacute;c với họ đến nhường n&agrave;o. Th&ocirc;ng qua đơn xin việc bạn viết, nh&agrave; tuyển dụng cũng sẽ tiết kiệm được thời gian v&agrave; chi ph&iacute; hơn cho việc s&agrave;ng lọc c&aacute;c ứng vi&ecirc;n thực sự ph&ugrave; hợp với vị tr&iacute; m&agrave; họ đang tuyển dụng.&nbsp;</span></p>\n\n<h2 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">2. Mẫu đơn xin việc ng&agrave;nh bất động sản c&oacute; thể tạo theo h&igrave;nh thức n&agrave;o?</span></h2>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Đơn xin việc bất động sản n&oacute;i chung th&igrave; bản chất v&agrave; h&igrave;nh thức cũng giống như c&aacute;c </span>\n<style type=\"text/css\"><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->\n</style>\n<span style=\"font-size:14px;\">đơn xin việc mẫu chuẩn kh&aacute;c, bạn c&oacute; thể thực hiện việc tạo ra một <strong>mẫu đơn xin việc ng&agrave;nh bất động sản</strong> th&ocirc;ng qua c&aacute;c h&igrave;nh thức sau:</span></p>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">2.1. Đơn xin việc viết tay ng&agrave;nh bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Một h&igrave;nh thức truyền thống, nhưng lại thể hiện một c&aacute;ch &ldquo;trần trụi&rdquo; nhất những ước mơ v&agrave; mong muốn được cống hiến của bạn - Đơn xin việc viết tay ng&agrave;nh bất động sản. Tất nhi&ecirc;n, n&oacute; ho&agrave;n to&agrave;n được viết bằng tay, người t&igrave;m việc sẽ trực tiếp sử dụng b&uacute;t v&agrave; giấy để s&aacute;ng tạo ra nội dung, sắp xếp c&aacute;c bố cục v&agrave; thể hiện nhu cầu th&ocirc;ng qua lối h&agrave;nh văn của ri&ecirc;ng m&igrave;nh. Đơn xin việc viết tay tuy mất kh&aacute; nhiều thời gian của bạn, nhưng n&oacute; ho&agrave;n to&agrave;n c&oacute; thể mang lại được những kết quả đ&aacute;ng mừng. Vậy bạn đ&atilde; biết <strong>c&aacute;ch viết đơn xin việc viết tay ng&agrave;nh bất động sản</strong>? Dưới đ&acirc;y l&agrave; một số lưu &yacute; khi bạn viết tay đơn xin việc:</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-đơn xin việc viết tay\" height=\"532\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/don-xin-viec-viet-tay.jpg\" width=\"800\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Tr&igrave;nh b&agrave;y thật ngắn gọn nhưng đầy đủ về c&aacute;c dữ liệu c&aacute; nh&acirc;n li&ecirc;n quan đến bạn. Đặc biệt, bạn kh&ocirc;ng n&ecirc;n sử dụng từ ngữ viết tắt trong đơn xin việc. Bởi, đ&ocirc;i khi nh&agrave; tuyển dụng sẽ nhận ra bạn l&agrave; một người kh&ocirc;ng ki&ecirc;n nhẫn v&agrave; c&oacute; t&iacute;nh cẩu thả. Trong khi, hai yếu tố n&agrave;y được xem l&agrave; &ldquo;cấm kỵ&rdquo; trong lĩnh vực kinh doanh bất động sản.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- H&atilde;y ch&uacute; &yacute; một ch&uacute;t về c&aacute;ch chọn m&agrave;u mực b&uacute;t để viết đơn xin việc bất động sản, chỉ n&ecirc;n sử dụng một trong hai loại mực: đen v&agrave; xanh để viết. C&ograve;n nữa, bạn chỉ n&ecirc;n tr&igrave;nh b&agrave;y một c&aacute;ch đơn giản, tinh tế nhất, kh&ocirc;ng n&ecirc;n sử dụng c&aacute;c m&agrave;u mực đa sắc để t&ocirc; đậm hay vẽ vời tr&ecirc;n đơn xin việc. Bất động sản cần những c&aacute; nh&acirc;n c&oacute; độ chuy&ecirc;n nghiệp cao, c&aacute;ch m&agrave; bạn từ t&ocirc; vẽ cho bản th&acirc;n th&igrave; kh&ocirc;ng chuy&ecirc;n nghiệp ch&uacute;t n&agrave;o.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- H&atilde;y chuẩn bị một tờ giấy A4 v&agrave; một c&acirc;y b&uacute;t mua mới để viết đơn xin việc bất động sản. Giữa chừng hết mực hay giấy r&aacute;ch th&igrave; bạn sẽ kh&ocirc;ng &ldquo;may mắn&rdquo; đ&acirc;u đấy. Một đơn xin việc c&oacute; h&igrave;nh thức đẹp th&igrave; ngay từ đầu phải thống nhất v&agrave; đồng đều về m&agrave;u chữ cũng như n&eacute;t b&uacute;t.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Đơn xin việc bất động sản, để tạo sự chuy&ecirc;n nghiệp, bạn n&ecirc;n đầu tư một ch&uacute;t c&ocirc;ng sức v&agrave; thời gian để tr&igrave;nh b&agrave;y n&oacute; một c&aacute;ch sạch sẽ, đẹp đẽ nhất.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Nếu bạn muốn nổi bật nhất trong một &ldquo;rừng đơn xin việc&rdquo; của c&aacute;c ứng vi&ecirc;n kh&aacute;c, c&oacute; thể tự tạo ri&ecirc;ng cho m&igrave;nh một cấu tr&uacute;c, một form đơn xin việc m&agrave; bạn cảm thấy tạo được sự thu h&uacute;t với nh&agrave; tuyển dụng.</span></p>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">2.2. Đơn xin việc đ&aacute;nh m&aacute;y ng&agrave;nh bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Đơn xin việc đ&aacute;nh m&aacute;y ng&agrave;nh bất động sản hay c&oacute; thể hiểu l&agrave; một <strong>mẫu đơn xin việc ng&agrave;nh bất động sản file word</strong>, ch&iacute;nh l&agrave; h&igrave;nh thức thứ hai của mẫu đơn xin việc n&agrave;y m&agrave; bạn c&oacute; thể sử dụng để ứng tuyển. Bạn sẽ thực hiện việc soạn thảo văn bản tr&ecirc;n m&aacute;y t&iacute;nh mẫu đơn xin việc n&agrave;y.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Tuy nhi&ecirc;n cần lưu &yacute; khi viết đơn xin việc đ&aacute;nh m&aacute;y ng&agrave;nh bất động sản l&agrave;, c&aacute;c lỗi về tin học văn ph&ograve;ng, c&aacute;ch bạn thao t&aacute;c tr&ecirc;n c&aacute;c phần mềm soạn thảo đảm bảo sao cho ph&ugrave; hợp v&agrave; đẹp mắt nhất c&oacute; thể. Chẳng hạn như c&aacute;ch bạn chọn ph&ocirc;ng chữ, sắp xếp c&aacute;c bố cục, chọn cỡ chữ, c&aacute;ch căn lề, xuống d&ograve;ng, c&aacute;c k&yacute; tự khi soạn thảo,... đều phải hết sức cẩn thận. Chuy&ecirc;n vi&ecirc;n kinh doanh bất động sản cũng cần c&oacute; kỹ năng tin học văn ph&ograve;ng, đ&ocirc;i khi phải thực hiện x&acirc;y dựng c&aacute;c b&aacute;o c&aacute;o định kỳ với l&atilde;nh đạo, v&igrave; vậy th&ocirc;ng qua c&aacute;ch bạn tr&igrave;nh b&agrave;y một mẫu đơn xin việc đ&aacute;nh m&aacute;y, họ c&oacute; thể nh&igrave;n ra được bạn c&oacute; thao t&aacute;c chuẩn tr&ecirc;n c&aacute;c phương tiện c&ocirc;ng nghệ hay kh&ocirc;ng đấy!</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-đơn xin việc đánh máy\" height=\"372\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/don-xin-viec-danh-may(2).jpg\" width=\"800\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Đối với h&igrave;nh thức n&agrave;y, một mẫu đơn xin việc bất động sản ho&agrave;n to&agrave;n c&oacute; thể được bạn nhanh ch&oacute;ng tạo ra. N&oacute; vừa tiết kiệm cho bạn nhiều thời gian, c&ocirc;ng sức, vừa thể hiện được t&iacute;nh hiện đại, c&ocirc;ng nghệ, chuy&ecirc;n nghiệp, đảm bảo đơn xin việc của bạn sạch sẽ ho&agrave;n to&agrave;n, kh&ocirc;ng phải mất c&ocirc;ng viết đi viết lại.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><strong><span style=\"font-size:14px;\"><a href=\"https://timviec365.vn/viec-lam-kd-bat-dong-san-c33v0\" id=\"xt\">Tuyển dụng bất động sản</a></span></strong></p>\n\n<h2 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">3. C&aacute;ch để bạn s&aacute;ng tạo một nội dung ho&agrave;n hảo cho mẫu đơn xin việc ng&agrave;nh bất động sản</span></h2>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Ng&agrave;y nay, khi đơn xin việc c&agrave;ng chứng minh được tầm quan trọng của n&oacute; trong mắt c&aacute;c nh&agrave; tuyển dụng, th&igrave; n&oacute; được cung cấp sẵn ở rất nhiều địa điểm kh&aacute;c nhau. Tuy nhi&ecirc;n, với ng&agrave;nh nghề bất động sản v&agrave; mục đ&iacute;ch của bạn khi sử dụng mẫu đơn xin việc ng&agrave;nh bất động sản, bạn kh&ocirc;ng n&ecirc;n chỉ dừng lại ở việc tải c&aacute;c mẫu sẵn c&oacute; về v&agrave; sử dụng lu&ocirc;n những nội dung ban đầu. H&atilde;y l&agrave;m cho đơn xin việc của bạn c&oacute; điểm nhấn, tạo sự kh&aacute;c biệt bằng c&aacute;ch biến tấu v&agrave; s&aacute;ng tạo nội dung cho n&oacute; sao cho ph&ugrave; hợp nhất với ng&agrave;nh bất động sản. Kh&ocirc;ng để bạn đợi l&acirc;u nữa, dưới đ&acirc;y l&agrave; một số gợi &yacute;:</span></p>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">3.1. Lời mở đầu của đơn xin việc bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Dựa v&agrave;o những dữ liệu bạn đ&atilde; thu thập ở tin đăng tuyển của c&aacute;c doanh nghiệp kinh doanh bất động sản, hay c&aacute;ch m&agrave; bạn tự t&igrave;m hiểu tr&ecirc;n c&aacute;c website ch&iacute;nh thức của doanh nghiệp hoặc mạng x&atilde; hội của doanh nghiệp. H&atilde;y x&aacute;c định c&aacute; nh&acirc;n l&agrave; người đứng đầu hay bộ phận tuyển dụng trực tiếp c&ocirc;ng việc để bạn gửi hồ sơ xin việc đến. Lời mở đầu lu&ocirc;n l&agrave; một lời ch&agrave;o, một đơn xin việc bất động sản chuy&ecirc;n nghiệp n&ecirc;n c&oacute; lời mở đầu, n&oacute;i r&otilde; ra cụ thể v&agrave; ch&iacute;nh x&aacute;c họ t&ecirc;n, cũng như chức danh của người đứng đầu doanh nghiệp hay người tuyển dụng trực tiếp bạn. Muốn c&oacute; được th&ocirc;ng tin ch&iacute;nh x&aacute;c n&agrave;y, bạn phải bỏ ra một ch&uacute;t thời gian để t&igrave;m hiểu, c&ograve;n nếu kh&ocirc;ng chắc chắn về dữ liệu m&igrave;nh đ&atilde; thu thập, h&atilde;y để t&ecirc;n gọi của doanh nghiệp v&agrave;o. Chẳng hạn như &ldquo;K&iacute;nh gửi: Bộ phận/Ph&ograve;ng nh&acirc;n sự C&ocirc;ng ty địa ốc ABC&rdquo;,...</span></p>\n\n<blockquote>\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Xem Th&ecirc;m: <a href=\"https://timviec365.vn/cv365/don-xin-viec-nha-hang-khach-san\"><strong>Đơn xin việc nh&agrave; h&agrave;ng - Kh&aacute;ch sạn</strong></a></span></p>\n</blockquote>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">3.2. Đoạn mở đầu của đơn xin việc bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Đoạn mở đầu l&agrave; rất quan trọng với một mẫu đơn xin việc, cũng giống như c&aacute;ch bạn viết một b&agrave;i văn nghị luận hay một b&agrave;i b&aacute;o, mở đầu ch&iacute;nh l&agrave; c&aacute;ch bạn c&oacute; thể dẫn dắt, tạo sự thu h&uacute;t của người đọc đến phần nội dung ch&iacute;nh hay nội dung trọng t&acirc;m. Đoạn mở đầu trong đơn xin việc ng&agrave;nh bất động sản ch&iacute;nh l&agrave; l&yacute; do bạn thực hiện việc gửi l&aacute; đơn n&agrave;y. Hay cũng c&oacute; thể l&agrave; c&aacute;ch m&agrave; bạn tiếp cận với nh&agrave; tuyển dụng ra sao.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Đoạn mở đầu trong đơn xin việc bạn n&ecirc;n tối ưu h&oacute;a nhất một c&aacute;ch c&oacute; thể, tốt nhất chỉ tr&igrave;nh b&agrave;y n&oacute; trong một đến hai c&acirc;u. Chằng hạn như: &ldquo;T&ocirc;i biết được qu&yacute; doanh nghiệp hiện đang c&oacute; nhu cầu tuyển dụng vị tr&iacute; chuy&ecirc;n vi&ecirc;n kinh doanh bất động sản th&ocirc;ng qua website Timviec365.vn v&agrave; t&ocirc;i rất quan t&acirc;m đến vị tr&iacute; c&ocirc;ng việc n&agrave;y&rdquo;.</span></p>\n\n<blockquote>\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Xem Th&ecirc;m:&nbsp; <a href=\"https://timviec365.vn/cv365/don-xin-viec-y-te-duoc\"><strong>Đơn xin việc y tế - Y dược</strong></a></span></p>\n</blockquote>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">3.3. Nội dung trọng t&acirc;m của đơn xin việc bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Nội dung trọng t&acirc;m đ&uacute;ng như t&ecirc;n gọi của n&oacute;, n&oacute; l&agrave; phần mấu chốt v&agrave; quan trọng nhất trong một mẫu <strong>đơn xin việc bất động sản</strong>. Đối với phần n&agrave;y, bạn n&ecirc;n thể hiện những nội dung m&agrave; bạn cho l&agrave; thế mạnh, ưu điểm của bạn để l&agrave;m to&aacute;t l&ecirc;n sự ph&ugrave; hợp của bạn đối với vị tr&iacute; m&agrave; doanh nghiệp đang tuyển dụng. Những yếu tố bạn c&oacute; thể đề cập đến nội dung n&agrave;y c&oacute; thể l&agrave;:</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Kinh nghiệm từng trải của bạn v&agrave; n&oacute; rất tốt cho c&ocirc;ng việc n&agrave;y: Bất động sản hiện c&oacute; rất &iacute;t cơ sở gi&aacute;o dục đ&agrave;o tạo một c&aacute;ch b&agrave;i bản chuy&ecirc;n s&acirc;u, m&agrave; kinh nghiệm hầu như được t&iacute;ch lũy qua qu&aacute; tr&igrave;nh trải nghiệm c&aacute;c c&ocirc;ng việc thực tế. Ch&iacute;nh v&igrave; vậy, trong đơn xin việc bất động sản, bạn c&oacute; thể tận dụng sự trải nghiệm của m&igrave;nh, bao gồm cả những trải nghiệm th&agrave;nh c&ocirc;ng v&agrave; thất bại trong c&ocirc;ng việc. V&iacute; như, bạn đ&atilde; từng ở vị tr&iacute; của một m&ocirc;i giới vi&ecirc;n nh&agrave; đất tự do, hay đ&atilde; từng trải nghiệm c&ocirc;ng việc li&ecirc;n quan tại một doanh nghiệp bất động sản kh&aacute;c,... d&ugrave; bạn l&agrave;m ở vị tr&iacute; n&agrave;o, l&agrave;m tự do hay l&agrave;m thu&ecirc; th&igrave; những sự trải nghiệm đ&oacute; nhất định c&oacute; &iacute;ch cho c&ocirc;ng việc trong tương lai. V&agrave; khi bạn tr&igrave;nh b&agrave;y như vậy, hẳn đơn xin việc của bạn sẽ g&acirc;y được ấn tượng với nh&agrave; tuyển dụng.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-nội dung trọng tâm\" height=\"1119\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/noi-dung-trong-tam-don-xin-viec.png\" width=\"792\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Tại sao bạn chọn c&ocirc;ng ty để ứng tuyển cho vị tr&iacute; c&ocirc;ng việc n&agrave;y?: H&atilde;y thử trả lời c&acirc;u hỏi n&agrave;y bằng c&aacute;ch tr&igrave;nh b&agrave;y những ưu điểm v&agrave; nhấn mạnh vấn đề văn h&oacute;a, ch&iacute;nh s&aacute;ch, quy chế v&agrave; to&agrave;n bộ định hướng, mục ti&ecirc;u của doanh nghiệp bạn đang ứng tuyển l&agrave; ph&ugrave; hợp nhất với nguyện vọng cũng như mục ti&ecirc;u c&aacute; nh&acirc;n của bạn.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Thế mạnh m&agrave; bạn nhận định bạn l&agrave; ứng cử vi&ecirc;n tiềm năng nhất cho vị tr&iacute; c&ocirc;ng việc n&agrave;y: bất động sản lu&ocirc;n cần những thế mạnh ch&iacute;nh l&agrave; những kỹ năng bạn đ&atilde; trang bị rất nhiều, rất tốt th&igrave; bạn mới c&oacute; thể tăng cao mức thu nhập c&aacute; nh&acirc;n. Lưu &yacute; về việc đưa những kỹ năng ph&ugrave; hợp với y&ecirc;u cầu của c&ocirc;ng việc bạn đang ứng tuyển, c&oacute; thể đ&oacute; l&agrave; những kỹ năng quan trọng như: am hiểu th&agrave;nh thạo thị trường bất động sản, c&oacute; khả năng ph&acirc;n t&iacute;ch thị trường linh hoạt; kỹ năng đ&agrave;m ph&aacute;n v&agrave; thuyết phục kh&aacute;ch h&agrave;ng; năng lực duy tr&igrave; v&agrave; ph&aacute;t triển c&aacute;c mối quan hệ; kỹ năng giao tiếp kh&ocirc;n kh&eacute;o;... Tr&igrave;nh b&agrave;y thật t&oacute;m gọn nhất c&oacute; thể, khi bạn đưa những thế mạnh của bạn v&agrave;o, n&oacute; c&oacute; thể l&agrave;m nổi bật l&ecirc;n được sự ph&ugrave; hợp của bạn, nh&agrave; tuyển dụng chỉ cần lướt qua l&agrave; họ c&oacute; thể đ&aacute;nh gi&aacute; được phần n&agrave;o.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Mục ti&ecirc;u trong tương lai của bạn l&agrave; g&igrave;?: một ng&agrave;nh nghề tiềm ẩn nhiều sự th&aacute;ch thức v&agrave; sự đ&agrave;o thải v&ocirc; c&ugrave;ng khủng khiếp. V&igrave; vậy, c&aacute;ch bạn n&oacute;i về mục ti&ecirc;u phấn đấu rất quan trọng trong đơn xin việc. Th&ocirc;ng qua đ&oacute;, nh&agrave; tuyển dụng c&oacute; thể thấy được tham vọng v&agrave; sự kh&aacute;t khao được bước l&ecirc;n đỉnh vinh quang của bạn. Mục ti&ecirc;u d&ugrave; ngắn hạn hay d&agrave;i hạn cũng n&ecirc;n được bạn tr&igrave;nh b&agrave;y t&oacute;m tắt nhất một c&aacute;ch c&oacute; thể, d&ugrave;ng những từ ngữ sắc b&eacute;n, quyết liệt, thể hiện bạn l&agrave; một người c&oacute; tầm nh&igrave;n, c&oacute; định hướng v&agrave; c&oacute; biết c&aacute;ch l&agrave;m thế n&agrave;o để đạt được kế hoạch đề ra.&nbsp;</span></p>\n\n<h3 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">3.4. Phần cuối của đơn xin việc bất động sản</span></h3>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">C&oacute; mở b&agrave;i, th&acirc;n b&agrave;i th&igrave; đương nhi&ecirc;n với một l&aacute; đơn xin việc cũng cần c&oacute; phần kết. Tại đ&acirc;y, h&atilde;y để lại cho nh&agrave; tuyển dụng biết những c&aacute;ch để li&ecirc;n hệ với bạn. C&ugrave;ng với đ&oacute;, tổng kết v&agrave; t&oacute;m gọn lại to&agrave;n bộ nội dung của đơn xin việc bằng một đến hai c&acirc;u n&oacute;i l&ecirc;n mức độ mong muốn của bạn khi được doanh nghiệp nhận v&agrave;o l&agrave;m việc. Đừng qu&ecirc;n nhắc đến c&aacute;c giấy tờ kh&aacute;c như bản CV chẳng hạn, để doanh nghiệp c&oacute; thể dễ d&agrave;ng kiểm tra v&agrave; đối chiếu.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><strong><span style=\"font-size:14px;\"><a href=\"https://timviec365.vn/cv-xin-viec\" id=\"xt\" target=\"_blank\">CV</a></span></strong></p>\n\n<h2 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">4. Bật m&iacute; c&aacute;ch viết đơn xin việc ng&agrave;nh bất động sản bằng tiếng Anh</span></h2>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Như c&aacute;c l&agrave; <a href=\"https://timviec365.vn/cv365/don-xin-viec-bien-phien-dich\"><strong>đơn xin việc Bi&ecirc;n - Phi&ecirc;n dịch</strong></a>, <a href=\"https://timviec365.vn/cv365/don-xin-viec-xuat-nhap-khau\"><strong>đơn xin việc xuất nhập khẩu</strong></a>, <strong><a href=\"https://timviec365.vn/cv365/don-xin-viec-it\">đơn xin việc IT</a></strong>,... bạn n&ecirc;n&nbsp;đầu tư th&ecirc;m một mẫu đơn xin việc ng&agrave;nh bất động sản bằng tiếng Anh để tăng th&ecirc;m cơ hội được tuyển dụng v&agrave;o c&aacute;c doanh nghiệp bất động sản nước ngo&agrave;i. Khi viết mẫu<strong> đơn xin việc bất động sản bằng tiếng Anh</strong>, bạn n&ecirc;n tham khảo những lưu &yacute; như sau:</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- N&ecirc;n mở đầu thư với một lời ch&agrave;o ngắn gọn nhưng cụ thể nhất về người nhận mẫu đơn xin việc n&agrave;y. H&atilde;y sử dụng cấu tr&uacute;c: &ldquo;Dear + t&ecirc;n gọi của c&aacute; nh&acirc;n người phụ tr&aacute;ch tuyển dụng của doanh nghiệp + dấu phẩy hay dấu chấm). Như đ&atilde; n&oacute;i ở tr&ecirc;n, h&atilde;y chắc chắn về chức danh cũng như t&ecirc;n gọi của c&aacute; nh&acirc;n người tuyển dụng, giới t&iacute;nh của họ để sử dụng &ldquo; Mr, Dr hay Ms&rdquo;. Hay bạn cũng c&oacute; thể viết &ldquo;Dear Hiring Manager&rdquo; hay &ldquo;Dear + t&ecirc;n gọi doanh nghiệp&rdquo; nếu kh&ocirc;ng chắc chắn về một c&aacute;i t&ecirc;n cụ thể n&agrave;o đ&oacute;.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-đơn xin việc bằng tiếng anh\" height=\"533\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/don-xin-viec-bang-tieng-anh(1).png\" width=\"800\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Đoạn mở đầu n&ecirc;n viết khoảng 1 đến hai d&ograve;ng n&oacute;i về l&yacute; do bạn viết đơn xin việc. Chẳng hạn như bạn đang ứng tuyển ở vị tr&iacute; chuy&ecirc;n vi&ecirc;n b&aacute;n h&agrave;ng hay chuy&ecirc;n vi&ecirc;n kinh doanh bất động sản, h&atilde;y viết l&agrave;: &ldquo;I am writing to you with regards to the position within your company for Sales Excutive&rsquo;.</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Nội dung trọng t&acirc;m trong mẫu đơn xin việc tiếng Anh ng&agrave;nh bất động sản cũng tương tự như mẫu đơn xin việc bằng tiếng Việt, tuy nhi&ecirc;n bạn cần lưu &yacute; việc sử dụng những từ vựng chuy&ecirc;n ng&agrave;nh, tr&igrave;nh b&agrave;y c&acirc;u văn theo cấu tr&uacute;c đơn giản, v&iacute; dụ như mục kinh nghiệm, bạn phải d&ugrave;ng cấu tr&uacute;c th&igrave; qu&aacute; khứ, c&ograve;n phần mục ti&ecirc;u nghề nghiệp, bạn n&ecirc;n d&ugrave;ng cấu tr&uacute;c th&igrave; tương lai,...&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">- Cuối đơn xin việc bất động sản bằng tiếng Anh, h&atilde;y n&ecirc;u n&ecirc;n c&aacute;ch m&agrave; bạn hy vọng, mong muốn được doanh nghiệp nhận v&agrave;o l&agrave;m. Sử dụng từ mở đầu như &ldquo;Best&rdquo; hay &ldquo;Sincerely&rdquo;. Chỉ cần như vậy l&agrave; bạn đ&atilde; sở hữu trong tay một Cover Letter bất động sản chuy&ecirc;n nghiệp rồi.&nbsp;</span></p>\n\n<blockquote>\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Xem Th&ecirc;m: <a href=\"https://timviec365.vn/cv365/don-xin-viec-noi-that\"><strong>Đơn xin việc nội thất</strong></a></span></p>\n</blockquote>\n\n<h2 dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">5. Timviec365.vn - Tải mẩu đơn xin việc ng&agrave;nh bất động sản chỉ l&agrave; chuyện nhỏ&nbsp;&nbsp; &nbsp;</span></h2>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Khi đ&atilde; đọc đến đ&acirc;y, chắc hẳn bạn đ&atilde; nhận thức được tầm quan trọng của một mẫu đơn xin việc ng&agrave;nh bất động sản rồi, đ&uacute;ng kh&ocirc;ng n&agrave;o? Đối với c&aacute;c bạn sinh vi&ecirc;n mới ra trường, khi chưa được l&agrave;m quen nhiều với c&aacute;c kỹ năng v&agrave; sự chuẩn bị cho qu&aacute; tr&igrave;nh ứng tuyển, bao gồm cả đơn xin việc, th&igrave; cũng đừng qu&aacute; lo lắng. Bởi với Timviec365.vn - T<strong>ải mẫu đơn xin việc ng&agrave;nh quản bất động sản </strong>chỉ l&agrave; chuyện nhỏ.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><span style=\"font-size:14px;\"><img alt=\"đơn xin việc bất động sản-tải đơn xin việc tại timviec365vn\" height=\"404\" src=\"https://storage.timviec365.vn/timviec365/cv365/upload/images/tai-don-xin-viec-tai-timviec365vn.png\" width=\"800\" /></span></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Timviec365.vn - Địa điểm h&agrave;ng đầu cung cấp miễn ph&iacute; c&aacute;c mẫu đơn xin việc chuẩn v&agrave; đẹp nhất hiện nay. H&agrave;ng trăm mẫu đơn xin việc bất động sản&nbsp;</span><span style=\"font-size:14px;\">đa dạng ng&agrave;nh nghề, thiết kế, form đầy ấn tượng. B&ecirc;n cạnh đ&oacute;, c&ograve;n phong ph&uacute; lu&ocirc;n về mặt ng&ocirc;n ngữ đơn xin việc, như Trung, Anh, H&agrave;n, Nhật, Việt. Chỉ cần truy cập v&agrave;o website, chọn danh mục &ldquo;Hồ sơ xin việc&rdquo;, tiếp đến chọn &ldquo;đơn xin việc online&rdquo;. Như thế, bạn đ&atilde; c&oacute; thể trải nghiệm c&aacute;c t&iacute;nh năng chọn, chỉnh sửa nội dung theo mẫu v&agrave; tải về mẫu đơn xin việc bất động sản đẹp nhất để &ldquo;đốn tim&rdquo; nh&agrave; tuyển dụng rồi.&nbsp;</span></p>\n\n<p dir=\"ltr\" style=\"text-align: center;\"><strong><span style=\"font-size:14px;\"><a href=\"https://timviec365.vn/\" id=\"xt\" target=\"_blank\">Việc l&agrave;m</a></span></strong></p>\n\n<p dir=\"ltr\" style=\"text-align: justify;\"><span style=\"font-size:14px;\">Tr&ecirc;n đ&acirc;y l&agrave; to&agrave;n bộ kiến thức v&agrave; b&iacute; quyết ch&uacute;ng t&ocirc;i muốn th&ocirc;ng tin đến bạn về c&aacute;ch để sở hữu một mẫu đơn xin việc ng&agrave;nh bất động sản ấn tượng. Chỉ một v&agrave;i thao t&aacute;c nhỏ tr&ecirc;n Timviec365.vn, ch&uacute;c bạn đọc th&agrave;nh c&ocirc;ng v&agrave; may mắn với mẫu đơn xin việc của m&igrave;nh!</span></p>\n\n<p><iframe allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen=\"\" frameborder=\"0\" height=\"534\" src=\"https://www.youtube.com/embed/1o5ab3oya4o\" width=\"100%\"></iframe></p>\n<style type=\"text/css\"><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->\n</style>\n",
                "cid": 33,
                "meta_title": "Mẫu đơn xin việc dành cho nhân viên bất động sản",
                "meta_key": "Đơn xin việc nhân viên bất động sản",
                "meta_des": "Nếu bạn đang muốn ứng tuyển vào công việc thuộc lĩnh vực bất động sản, vậy làm thế nào để tạo ra một mẫu đơn xin việc bất động sản? Hãy tham khảo bài viết dưới đây",
                "meta_tt": "Đơn xin việc Bất động sản tại timviec365.vn giúp các bạn dễ dàng lựa chọn được nhiều mẫu đơn xin việc phù hợp để các bạn có thể lựa chọn. Đến ngay với đơn xin việc bất động sản trên hệ thống trang website timviec365.vn để tận hưởng những điều lý thú nhất, góp phần mang tới cho chính mình những cơ hội việc làm hấp dẫn nhất trong lĩnh vực bất động sản.",
                "status": 1
            }
        ],
        "items": [
            {
                "_id": 157,
                "name": "Mẫu đơn xin việc bất động sản 08",
                "alias": "mau-don-xin-viec-bat-dong-san-08",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_157.jpg",
                "price": 0,
                "view": 374,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 155,
                "name": "Mẫu đơn xin việc bất động sản 07",
                "alias": "mau-don-xin-viec-bat-dong-san-07",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_155.jpg",
                "price": 0,
                "view": 183,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 153,
                "name": "Mẫu đơn xin việc bất động sản 06",
                "alias": "mau-don-xin-viec-bat-dong-san-06",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_153.jpg",
                "price": 0,
                "view": 72,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 151,
                "name": "Mẫu đơn xin việc bất động sản 05",
                "alias": "mau-don-xin-viec-bat-dong-san-05",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_151.jpg",
                "price": 0,
                "view": 42,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 149,
                "name": "Mẫu đơn xin việc bất động sản 04",
                "alias": "mau-don-xin-viec-bat-dong-san-04",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_149.jpg",
                "price": 0,
                "view": 52,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 147,
                "name": "Mẫu đơn xin việc bất động sản 03",
                "alias": "mau-don-xin-viec-bat-dong-san-03",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_147.jpg",
                "price": 0,
                "view": 36,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 145,
                "name": "Mẫu đơn xin việc bất động sản 02",
                "alias": "mau-don-xin-viec-bat-dong-san-02",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_145.jpg",
                "price": 0,
                "view": 40,
                "love": 0,
                "download": 0,
                "cate_id": 9
            },
            {
                "_id": 143,
                "name": "Mẫu đơn xin việc bất động sản 01",
                "alias": "mau-don-xin-viec-bat-dong-san-01",
                "image": "https://storage.timviec365.vn/timviec365/cv365/upload/donxinviec/thumb/don_143.jpg",
                "price": 0,
                "view": 46,
                "love": 0,
                "download": 1,
                "cate_id": 9
            }
        ],
        "count": 8
    },
    "error": null
}
export const resInfor = {
    "data": {
        "result": true,
        "message": "Hiển thị chi tiết ứng viên thành công",
        "thong_tin": {
            "isOnline": 1,
            "lastActivedAt": "2024-01-13T09:48:51.000Z",
            "use_id": 1111207307,
            "use_email": null,
            "use_phone_tk": "0963272602",
            "use_phone": "0963272602",
            "use_first_name": "Em Viết Hoàng",
            "use_update_time": 1705138731,
            "use_create_time": 1705134617,
            "use_logo": "",
            "use_email_lienhe": "hoangproo2k3@gmail.com",
            "use_gioi_tinh": 0,
            "use_birth_day": null,
            "use_city": 0,
            "use_quanhuyen": null,
            "use_address": "",
            "use_hon_nhan": 0,
            "use_view": 0,
            "use_authentic": 1,
            "cv_user_id": 1111207307,
            "cv_title": "nhân viên kinh doanh",
            "cv_exp": 0,
            "cv_muctieu": null,
            "cv_giai_thuong": null,
            "cv_hoat_dong": null,
            "cv_so_thich": null,
            "cv_cate_id": "30,45,107",
            "cv_city_id": "13",
            "cv_district_id": [],
            "cv_address": null,
            "cv_capbac_id": 0,
            "cv_money_id": 0,
            "cv_loaihinh_id": 0,
            "cv_kynang": null,
            "cv_tc_name": null,
            "cv_tc_cv": null,
            "cv_tc_phone": null,
            "cv_tc_email": null,
            "cv_tc_company": null,
            "cv_video": null,
            "cv_video_type": 0,
            "cv_hocvan": 0,
            "um_type": 0,
            "um_min_value": null,
            "um_max_value": null,
            "um_unit": 0,
            "profileDegree": [],
            "profileNgoaiNgu": [],
            "profileExperience": [],
            "star3": 0,
            "time_active_star3": 0,
            "user_xac_thuc": null,
            "use_show": 1,
            "chat365_id": 10116448,
            "candidate": {
                "use_type": 0,
                "user_reset_time": 0,
                "use_view": 0,
                "use_noti": 2,
                "use_show": 1,
                "time_hide": 0,
                "use_show_cv": 0,
                "use_active": 0,
                "use_td": 0,
                "use_check": 1,
                "use_test": 0,
                "use_badge": 0,
                "point_time_active": 0,
                "cv_title": "nhân viên kinh doanh",
                "cv_muctieu": null,
                "cv_kynang": null,
                "cv_giai_thuong": null,
                "cv_hoat_dong": null,
                "cv_so_thich": null,
                "cv_city_id": [
                    13
                ],
                "cv_district_id": [],
                "cv_address": null,
                "cv_cate_id": [
                    30,
                    45,
                    107
                ],
                "cv_cate_check": 0,
                "cv_check_sync_profile": 1,
                "cv_capbac_id": 0,
                "cv_money_id": 0,
                "cv_loaihinh_id": 0,
                "cv_time": 1,
                "cv_time_dl": 0,
                "um_type": 0,
                "um_min_value": null,
                "um_max_value": null,
                "um_unit": 0,
                "cv_tc_name": null,
                "cv_tc_cv": null,
                "cv_tc_dc": null,
                "cv_tc_phone": null,
                "cv_tc_email": null,
                "cv_tc_company": null,
                "cv_video": null,
                "cv_video_type": 0,
                "cv_video_active": 0,
                "use_ip": "",
                "percents": 12,
                "vip": 0,
                "check_create_use": 1,
                "check_create_cv": 0,
                "emp_id": 0,
                "profileDegree": [],
                "scan_audio": 0,
                "audio": [],
                "time_text": 0,
                "scan_elastic": 0,
                "anhsao_badge": 0,
                "star3": 0,
                "time_active_star3": 0,
                "_id": "65a24a199a640f9c456fa383",
                "profileNgoaiNgu": [],
                "profileExperience": []
            },
            "id_qlc": 22228519,
            "use_badge": 0,
            "anhsao_badge": 0,
            "level": 0,
            "status": "Đang online",
            "name_img": "",
            "name_img_hide": "",
            "fileUpLoad": ""
        },
        "bang_cap": [],
        "ngoai_ngu": [],
        "kinh_nghiem": [],
        "list_cv": [],
        "checkStatus": true,
        "voted": 0,
        "statusSaveCandi": false,
        "listBlog": [
            {
                "_id": "652329067bb8eaeb315bcbb9",
                "new_id": 1848,
                "new_title": "Nghề bảo vệ - xu hướng chọn việc làm tại Hà Nội hot nhất hiện nay",
                "new_title_rewrite": "nghe-bao-ve-xu-huong-chon-viec-lam-tai-ha-noi-hot-nhat-hien-nay",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2018/01/13/ngx1515835676.jpg"
            },
            {
                "_id": "6523290a79dcc7e72ec9a544",
                "new_id": 2298,
                "new_title": "Điểm danh những đồ dùng cần có của nghề bảo vệ mà bạn chưa biết",
                "new_title_rewrite": "nhung-do-dung-can-co-cua-nghe-bao-ve",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2018/04/07/crj1523064422.jpg"
            },
            {
                "_id": "6523290af9516b53ed718e9a",
                "new_id": 2302,
                "new_title": "Những điều ẩn sau lưng nghề bảo vệ mà chúng ta chưa biết",
                "new_title_rewrite": "nhung-dieu-ban-chua-biet-ve-nghe-bao-ve",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2018/04/09/can1523236503.jpg"
            },
            {
                "_id": "65232922e3f8d6dea1f92f8b",
                "new_id": 3917,
                "new_title": "An ninh trật tự là gì? Bảo vệ an ninh trật tự nước ta hiện nay",
                "new_title_rewrite": "an-ninh-trat-tu-la-gi",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2019/04/06/ylu1554548736.jpg"
            },
            {
                "_id": "65232924f9516b53ed71913d",
                "new_id": 4307,
                "new_title": "Cảnh vệ là gì? Những đối tượng được cảnh vệ là ai",
                "new_title_rewrite": "canh-ve-la-gi",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2019/05/14/sez1557840874.jpeg"
            },
            {
                "_id": "6523299cb1f9f2567a8300ef",
                "new_id": 10791,
                "new_title": "Khám phá bản mô tả công việc nhân viên giám sát sân bay mới nhất",
                "new_title_rewrite": "mo-ta-cong-viec-nhan-vien-giam-sat-san-bay",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2020/07/11/exp1594436145.jpg"
            },
            {
                "_id": "6523299dbb23be0ecae5a56c",
                "new_id": 10803,
                "new_title": "Thông tin về mô tả công việc vệ sĩ: Đầy đủ từ A tới Z cho bạn",
                "new_title_rewrite": "mo-ta-cong-viec-ve-si",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2020/07/13/qrf1594602915.jpg"
            },
            {
                "_id": "6523299ebb23be0ecae5a592",
                "new_id": 11015,
                "new_title": "Cập nhật bản mô tả công việc nhân viên bảo vệ đầy đủ từ A – Z",
                "new_title_rewrite": "mo-ta-cong-viec-nhan-vien-bao-ve",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2020/07/22/lld1595388229.jpg"
            },
            {
                "_id": "652329a0dec086a0edec25ba",
                "new_id": 11341,
                "new_title": "Mô tả công việc bảo vệ khách sạn - Cách tìm việc hiệu quả",
                "new_title_rewrite": "mo-ta-cong-viec-bao-ve-khach-san",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2020/08/08/sgg1596881079.jpg"
            },
            {
                "_id": "652329a3e3f8d6dea1f93c01",
                "new_id": 11663,
                "new_title": "Mô tả công việc nhân viên an ninh khách sạn - Security làm gì?",
                "new_title_rewrite": "mo-ta-cong-viec-nhan-vien-an-ninh-khach-san-security-lam-gi",
                "new_picture": "https://storage.timviec365.vn/timviec365/pictures/news/2020/08/21/srz1597999447.jpg"
            }
        ],
        "imagesCandi": []
    },
    "error": null
}